apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-blkio-limiter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-blkio-limiter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-blkio-limiter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-blkio-limiter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-blkio-limiter.serviceAccountName" . }}
      hostPID: true
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: host-cgroup
              mountPath: /host-cgroup
            - name: host-proc
              mountPath: /host-proc
              readOnly: true
      volumes:
        - name: host-cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
