apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-blkio-limiter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-blkio-limiter.labels" . | nindent 4 }}
