//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLimits) DeepCopyInto(out *DeviceLimits) {
	*out = *in
	if in.ReadBPS != nil {
		in, out := &in.ReadBPS, &out.ReadBPS
		*out = new(int64)
		**out = **in
	}
	if in.WriteBPS != nil {
		in, out := &in.WriteBPS, &out.WriteBPS
		*out = new(int64)
		**out = **in
	}
	if in.ReadIOPS != nil {
		in, out := &in.ReadIOPS, &out.ReadIOPS
		*out = new(int64)
		**out = **in
	}
	if in.WriteIOPS != nil {
		in, out := &in.WriteIOPS, &out.WriteIOPS
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLimits.
func (in *DeviceLimits) DeepCopy() *DeviceLimits {
	if in == nil {
		return nil
	}
	out := new(DeviceLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOLimiter) DeepCopyInto(out *IOLimiter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOLimiter.
func (in *IOLimiter) DeepCopy() *IOLimiter {
	if in == nil {
		return nil
	}
	out := new(IOLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOLimiter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOLimiterList) DeepCopyInto(out *IOLimiterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOLimiter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOLimiterList.
func (in *IOLimiterList) DeepCopy() *IOLimiterList {
	if in == nil {
		return nil
	}
	out := new(IOLimiterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOLimiterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOLimiterSpec) DeepCopyInto(out *IOLimiterSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOLimiterSpec.
func (in *IOLimiterSpec) DeepCopy() *IOLimiterSpec {
	if in == nil {
		return nil
	}
	out := new(IOLimiterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOLimiterStatus) DeepCopyInto(out *IOLimiterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOLimiterStatus.
func (in *IOLimiterStatus) DeepCopy() *IOLimiterStatus {
	if in == nil {
		return nil
	}
	out := new(IOLimiterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOLimits) DeepCopyInto(out *IOLimits) {
	*out = *in
	if in.ReadBytesPerSecond != nil {
		in, out := &in.ReadBytesPerSecond, &out.ReadBytesPerSecond
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.WriteBytesPerSecond != nil {
		in, out := &in.WriteBytesPerSecond, &out.WriteBytesPerSecond
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReadIOPS != nil {
		in, out := &in.ReadIOPS, &out.ReadIOPS
		*out = new(int64)
		**out = **in
	}
	if in.WriteIOPS != nil {
		in, out := &in.WriteIOPS, &out.WriteIOPS
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOLimits.
func (in *IOLimits) DeepCopy() *IOLimits {
	if in == nil {
		return nil
	}
	out := new(IOLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedDevice) DeepCopyInto(out *OwnedDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedDevice.
func (in *OwnedDevice) DeepCopy() *OwnedDevice {
	if in == nil {
		return nil
	}
	out := new(OwnedDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIOLimit) DeepCopyInto(out *PodIOLimit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIOLimit.
func (in *PodIOLimit) DeepCopy() *PodIOLimit {
	if in == nil {
		return nil
	}
	out := new(PodIOLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodIOLimit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIOLimitList) DeepCopyInto(out *PodIOLimitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodIOLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIOLimitList.
func (in *PodIOLimitList) DeepCopy() *PodIOLimitList {
	if in == nil {
		return nil
	}
	out := new(PodIOLimitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodIOLimitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIOLimitSpec) DeepCopyInto(out *PodIOLimitSpec) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]PodVolumeLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIOLimitSpec.
func (in *PodIOLimitSpec) DeepCopy() *PodIOLimitSpec {
	if in == nil {
		return nil
	}
	out := new(PodIOLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIOLimitStatus) DeepCopyInto(out *PodIOLimitStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]OwnedDevice, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIOLimitStatus.
func (in *PodIOLimitStatus) DeepCopy() *PodIOLimitStatus {
	if in == nil {
		return nil
	}
	out := new(PodIOLimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodVolumeLimit) DeepCopyInto(out *PodVolumeLimit) {
	*out = *in
	in.Limits.DeepCopyInto(&out.Limits)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Contributions != nil {
		in, out := &in.Contributions, &out.Contributions
		*out = make([]VolumeContribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodVolumeLimit.
func (in *PodVolumeLimit) DeepCopy() *PodVolumeLimit {
	if in == nil {
		return nil
	}
	out := new(PodVolumeLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeContribution) DeepCopyInto(out *VolumeContribution) {
	*out = *in
	in.Limits.DeepCopyInto(&out.Limits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeContribution.
func (in *VolumeContribution) DeepCopy() *VolumeContribution {
	if in == nil {
		return nil
	}
	out := new(VolumeContribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeLimit) DeepCopyInto(out *VolumeLimit) {
	*out = *in
	in.Limits.DeepCopyInto(&out.Limits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeLimit.
func (in *VolumeLimit) DeepCopy() *VolumeLimit {
	if in == nil {
		return nil
	}
	out := new(VolumeLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStatus.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}
